spring:
  datasource:
    url: jdbc:postgresql://185.4.16.24:22016/postgres
    username: root
    password: ngxOnzCyA641mQKsHCrUJQ==
  hikari:
    max-lifetime: 18000000
    idle-timeout: 6000000
    validation-timeout: 50000

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    com.stockguard: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN
    org.hibernate.orm.jdbc.bind: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

jwt:
  secret: ${JWT_SECRET}
  expiration: 900000
  refresh:
    expiration: 2592000000

server:
  port: 8080
